(async function(){
  const user=await dcAuth.requireUser();if(!user)return;const profile=await dcAuth.getProfile(user.id).catch(()=>null);
  if(profile?.account_role!=='cmc_admin'){window.location.replace(profile?.account_role==='regional_leader'?'leader.html':'dashboard.html');return}
  dcAuth.renderRoleNavigation(profile,'plans');const sb=await dcAuth.getSupabaseClient();const token=(await sb.auth.getSession()).data?.session?.access_token||'';
  const library=document.getElementById('taskPlanLibrary'),message=document.getElementById('taskPlanLibraryMessage');
  try{const response=await fetch('/.netlify/functions/task-plan-admin',{headers:{Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Could not load task plans.');message.textContent='';library.innerHTML=data.templates.length?data.templates.map(card).join(''):'<div class="cmcCourseEmpty"><strong>No task plans yet.</strong><p>Create the first master template to begin.</p></div>';attach()}catch(error){message.textContent=error.message;message.classList.add('error')}
  function card(plan){const published=plan.status==='published';const sections=plan.cmc_task_plan_sections?.[0]?.count||0,tasks=plan.cmc_task_plan_tasks?.[0]?.count||0;return `<article class="cmcCourseAdminCard cmcTaskPlanLibraryCard"><div class="cmcCourseCardTop"><span class="cmcCourseStatus ${published?'published':'draft'}">${published?'Published':plan.status==='archived'?'Archived':'Draft'}</span><span>Version ${plan.version}</span></div><div><p class="cmcEyebrow">${escape(plan.stage_key)}</p><h3>${escape(plan.title)}</h3><p>${escape(plan.description||'Add a description for this task plan.')}</p><div class="cmcCourseRules"><span>${sections} phases</span><span>${tasks} tasks</span></div></div><div class="cmcCourseCardActions"><a href="task-plan-preview.html?id=${encodeURIComponent(plan.id)}">Preview</a><a href="task-plan-builder.html?id=${encodeURIComponent(plan.id)}">Edit plan</a><button type="button" data-duplicate="${plan.id}" data-title="${escape(plan.title)}">Duplicate</button></div></article>`}
  function attach(){library.querySelectorAll('[data-duplicate]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{const response=await fetch('/.netlify/functions/task-plan-admin',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'duplicate',id:button.dataset.duplicate,title:`Copy of ${button.dataset.title}`})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error);window.location.href=`task-plan-builder.html?id=${data.template.id}`}catch(error){message.textContent=error.message;message.classList.add('error');button.disabled=false}}))}
  function escape(value){return String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
})();
